name: Download and Commit File

permissions:
  contents: write  

on:
  push:
    branches: [main]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download file
        run: curl -L "https://example.com/file.zip" -o "file.zip"

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add file.html
          git commit -m "Add downloaded file"
          git push
